stages:
  - test
  - deploy

run_test:
  stage: test
  image: python
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pwd
    - python -m pytest pytest/

pages:
  stage: deploy
  image: sphinxdoc/sphinx
  before_script:
  - pip install -r requirements.txt
  - pip install sphinx-rtd-theme
  - pip install nbsphinx
  - pip install notebook
  - apt-get update && apt-get install -y git pandoc
  script:
  - sphinx-build -b html Docs public/
  artifacts:
    paths:
    - public



