image: python:3.6-alpine

pages:
  stage: deploy
  script:
  - mkdir public
  - pip install sphinx
  - pip install sphinx-rtd-theme
  - pip install nbsphinx
  - pip install pyzmq
  - pip install notebook
  - sphinx-build -b html Docs public/
  artifacts:
    paths:
    - public
  only:
  - master


